{"issues":[{"id":7189,"project":{"id":14,"name":"teuthology"},"tracker":{"id":2,"name":"Feature"},"status":{"id":1,"name":"New"},"priority":{"id":4,"name":"Normal"},"author":{"id":3,"name":"Sage Weil"},"fixed_version":{"id":271,"name":"v0.76"},"subject":"teuthology-kill: ability to zap the entire queue","description":"when the queue gets backed up by several days it is awkward to clear out the queue.\r\n\r\nbonus points for:\r\n- filtering by user\r\n- filtering by machine type","done_ratio":0,"custom_fields":[{"id":1,"name":"Source","value":"other"},{"id":3,"name":"Tags","value":""},{"id":5,"name":"Reviewed","value":""},{"id":6,"name":"User Impact","value":""}],"created_on":"2014-01-20T17:05:49Z","updated_on":"2014-01-20T17:06:31Z","story_points":null},{"id":7163,"project":{"id":14,"name":"teuthology"},"tracker":{"id":1,"name":"Bug"},"status":{"id":1,"name":"New"},"priority":{"id":6,"name":"Urgent"},"author":{"id":561,"name":"Tamilarasi muthamizhan"},"assigned_to":{"id":684,"name":"Sandon Van Ness"},"subject":"s3tests bootsrap fails in the nightlies","description":"logs: ubuntu@teuthology:/a/teuthology-2014-01-13_19:35:03-upgrade:small-next-testing-basic-vps/37349\r\n\r\nI think we had similar issue before and it was resolved.\r\nYehuda, could you please look at this one?\r\n\r\n\r\n<pre>\r\n2014-01-15T01:47:08.689 DEBUG:teuthology.orchestra.run:Running [10.214.138.111]: 'cd /home/ubuntu/cephtest/s3-tests && ./bootstrap'\r\n2014-01-15T01:47:09.750 INFO:teuthology.orchestra.run.out:[10.214.138.111]: The --no-site-packages flag is deprecated; it is now the default behavior.\r\n2014-01-15T01:47:09.751 INFO:teuthology.orchestra.run.out:[10.214.138.111]: New python executable in virtualenv/bin/python\r\n2014-01-15T01:47:10.769 INFO:teuthology.orchestra.run.out:[10.214.138.111]: Installing distribute.............................................................................................................................................................................................done.\r\n2014-01-15T01:47:11.166 INFO:teuthology.orchestra.run.out:[10.214.138.111]: Installing pip...............done.\r\n2014-01-15T01:47:12.641 INFO:teuthology.orchestra.run.out:[10.214.138.111]: Downloading/unpacking pip from https://pypi.python.org/packages/source/p/pip/pip-1.5.tar.gz#md5=6969b8a8adc4c7f7c5eb1707118f0686\r\n2014-01-15T01:47:12.642 INFO:teuthology.orchestra.run.out:[10.214.138.111]:   Running setup.py egg_info for package pip\r\n2014-01-15T01:47:12.642 INFO:teuthology.orchestra.run.out:[10.214.138.111]:\r\n2014-01-15T01:47:12.642 INFO:teuthology.orchestra.run.out:[10.214.138.111]:     warning: no files found matching 'pip/cacert.pem'\r\n2014-01-15T01:47:12.642 INFO:teuthology.orchestra.run.out:[10.214.138.111]:     warning: no files found matching '*.html' under directory 'docs'\r\n2014-01-15T01:47:12.642 INFO:teuthology.orchestra.run.out:[10.214.138.111]:     warning: no previously-included files matching '*.rst' found under directory 'docs/_build'\r\n2014-01-15T01:47:12.642 INFO:teuthology.orchestra.run.out:[10.214.138.111]:     no previously-included directories found matching 'docs/_build/_sources'\r\n2014-01-15T01:47:12.642 INFO:teuthology.orchestra.run.out:[10.214.138.111]: Installing collected packages: pip\r\n2014-01-15T01:47:12.642 INFO:teuthology.orchestra.run.out:[10.214.138.111]:   Found existing installation: pip 1.1\r\n2014-01-15T01:47:12.642 INFO:teuthology.orchestra.run.out:[10.214.138.111]:     Uninstalling pip:\r\n2014-01-15T01:47:12.642 INFO:teuthology.orchestra.run.out:[10.214.138.111]:       Successfully uninstalled pip\r\n2014-01-15T01:47:12.643 INFO:teuthology.orchestra.run.out:[10.214.138.111]:   Running setup.py install for pip\r\n2014-01-15T01:47:12.643 INFO:teuthology.orchestra.run.out:[10.214.138.111]:\r\n2014-01-15T01:47:12.643 INFO:teuthology.orchestra.run.out:[10.214.138.111]:     warning: no files found matching 'pip/cacert.pem'\r\n2014-01-15T01:47:12.643 INFO:teuthology.orchestra.run.out:[10.214.138.111]:     warning: no files found matching '*.html' under directory 'docs'\r\n2014-01-15T01:47:12.643 INFO:teuthology.orchestra.run.out:[10.214.138.111]:     warning: no previously-included files matching '*.rst' found under directory 'docs/_build'\r\n2014-01-15T01:47:12.643 INFO:teuthology.orchestra.run.out:[10.214.138.111]:     no previously-included directories found matching 'docs/_build/_sources'\r\n2014-01-15T01:47:12.643 INFO:teuthology.orchestra.run.out:[10.214.138.111]:     Installing pip script to /home/ubuntu/cephtest/s3-tests/virtualenv/bin\r\n2014-01-15T01:47:12.643 INFO:teuthology.orchestra.run.out:[10.214.138.111]:     Installing pip2.7 script to /home/ubuntu/cephtest/s3-tests/virtualenv/bin\r\n2014-01-15T01:47:12.643 INFO:teuthology.orchestra.run.out:[10.214.138.111]:     Installing pip2 script to /home/ubuntu/cephtest/s3-tests/virtualenv/bin\r\n2014-01-15T01:47:12.644 INFO:teuthology.orchestra.run.out:[10.214.138.111]: Successfully installed pip\r\n2014-01-15T01:47:12.644 INFO:teuthology.orchestra.run.out:[10.214.138.111]: Cleaning up...\r\n2014-01-15T01:47:13.038 INFO:teuthology.orchestra.run.out:[10.214.138.111]: Wheel installs require setuptools >= 0.8 for dist-info support.\r\n2014-01-15T01:47:13.038 INFO:teuthology.orchestra.run.out:[10.214.138.111]: pip's wheel support requires setuptools >= 0.8 for dist-info support.\r\n2014-01-15T01:47:13.039 INFO:teuthology.orchestra.run.out:[10.214.138.111]: Storing debug log for failure in /home/ubuntu/.pip/pip.log\r\n2014-01-15T01:47:13.055 ERROR:teuthology.contextutil:Saw exception from nested tasks\r\nTraceback (most recent call last):\r\n  File \"/home/teuthworker/teuthology-next/teuthology/contextutil.py\", line 25, in nested\r\n    vars.append(enter())\r\n  File \"/usr/lib/python2.7/contextlib.py\", line 17, in __enter__\r\n    return self.gen.next()\r\n  File \"/home/teuthworker/teuthology-next/teuthology/task/s3tests.py\", line 223, in configure\r\n    './bootstrap',\r\n  File \"/home/teuthworker/teuthology-next/teuthology/orchestra/remote.py\", line 47, in run\r\n    r = self._runner(client=self.ssh, **kwargs)\r\n  File \"/home/teuthworker/teuthology-next/teuthology/orchestra/run.py\", line 271, in run\r\n    r.exitstatus = _check_status(r.exitstatus)\r\n  File \"/home/teuthworker/teuthology-next/teuthology/orchestra/run.py\", line 267, in _check_status\r\n    raise CommandFailedError(command=r.command, exitstatus=status, node=host)\r\nCommandFailedError: Command failed on 10.214.138.111 with status 1: 'cd /home/ubuntu/cephtest/s3-tests && ./bootstrap'\r\n\r\n</pre>","start_date":"2014-01-15","done_ratio":0,"custom_fields":[{"id":1,"name":"Source","value":"Q/A"},{"id":2,"name":"Backport","value":""},{"id":3,"name":"Tags","value":""},{"id":4,"name":"Severity","value":"3 - minor"},{"id":5,"name":"Reviewed","value":""}],"created_on":"2014-01-16T00:47:58Z","updated_on":"2014-01-16T03:20:54Z"},{"id":7162,"project":{"id":14,"name":"teuthology"},"tracker":{"id":1,"name":"Bug"},"status":{"id":1,"name":"New"},"priority":{"id":5,"name":"High"},"author":{"id":561,"name":"Tamilarasi muthamizhan"},"assigned_to":{"id":684,"name":"Sandon Van Ness"},"subject":"dumpling package is missing in gitbuilder for fedora18","description":"logs: ubuntu@teuthology:/a/teuthology-2014-01-13_19:35:03-upgrade:small-next-testing-basic-vps\r\n\r\n<pre>\r\n[37346]  upgrade/small/rgw/{0-cluster/start.yaml 1-dumpling-install/dumpling.yaml 2-workload/s3tests.yaml 3-upgrade-sequence/upgrade-all.yaml 4-restart/restart.yaml 5-emperor-workload/final.yaml distro/fedora_18.yaml}\r\n-----------------------------------------------------------------\r\ntime:   56s\r\nlog:    http://qa-proxy.ceph.com/teuthology/teuthology-2014-01-13_19:35:03-upgrade:small-next-testing-basic-vps/37346/\r\nsentry: http://sentry.ceph.com/inktank/teuthology/search?q=da567fb94ae34550a93e7966a078e7b6\r\n\r\n    Command failed on 10.214.138.152 with status 8: 'wget\r\n    http://gitbuilder.ceph.com/ceph-rpm-fc18-x86_64-basic/ref/dumpling/noarch\r\n    /ceph-release-1-0.fc18.noarch.rpm'\r\n\r\n[37328]  upgrade/small/fs/{0-cluster/start.yaml 1-dumpling-install/dumpling.yaml 2-workload/blogbench.yaml 3-upgrade-sequence/upgrade-all.yaml 4-restart/restart.yaml 5-emperor-workload/emperor.yaml distro/fedora_18.yaml}\r\n-----------------------------------------------------------------\r\ntime:   81s\r\nlog:    http://qa-proxy.ceph.com/teuthology/teuthology-2014-01-13_19:35:03-upgrade:small-next-testing-basic-vps/37328/\r\nsentry: http://sentry.ceph.com/inktank/teuthology/search?q=b1cb5d2ceabe4bf28d1473ca8b94424f\r\n\r\n    Command failed on 10.214.138.106 with status 8: 'wget\r\n    http://gitbuilder.ceph.com/ceph-rpm-fc18-x86_64-basic/ref/dumpling/noarch\r\n    /ceph-release-1-0.fc18.noarch.rpm'\r\n\r\n[37334]  upgrade/small/rados/{0-cluster/start.yaml 1-dumpling-install/dumpling.yaml 2-workload/loadgenbig.yaml 3-upgrade-sequence/upgrade.yaml 4-restart/restart.yaml 5-emperor-workload/emperor.yaml distro/fedora_18.yaml}\r\n-----------------------------------------------------------------\r\ntime:   104s\r\nlog:    http://qa-proxy.ceph.com/teuthology/teuthology-2014-01-13_19:35:03-upgrade:small-next-testing-basic-vps/37334/\r\nsentry: http://sentry.ceph.com/inktank/teuthology/search?q=47b4cf244e20468a919b0b8bd3819940\r\n\r\n    Command failed on 10.214.138.127 with status 8: 'wget\r\n    http://gitbuilder.ceph.com/ceph-rpm-fc18-x86_64-basic/ref/dumpling/noarch\r\n    /ceph-release-1-0.fc18.noarch.rpm'\r\n</pre>","start_date":"2014-01-15","done_ratio":0,"custom_fields":[{"id":1,"name":"Source","value":"Q/A"},{"id":2,"name":"Backport","value":""},{"id":3,"name":"Tags","value":""},{"id":4,"name":"Severity","value":"3 - minor"},{"id":5,"name":"Reviewed","value":""}],"created_on":"2014-01-16T00:40:03Z","updated_on":"2014-01-21T04:23:07Z"},{"id":7155,"project":{"id":14,"name":"teuthology"},"tracker":{"id":1,"name":"Bug"},"status":{"id":1,"name":"New"},"priority":{"id":4,"name":"Normal"},"author":{"id":1332,"name":"Yuri Weinstein"},"assigned_to":{"id":57,"name":"Samuel Just"},"subject":"rados-dumpling \"Command failed\" error in nightly run 1/14/2014","description":"ubuntu@teuthology:/a/teuthology-2014-01-14_19:00:22-rados-dumpling-testing-basic-plana/38758\r\n\r\nError:\r\n\"ubuntu@teuthology:/a/teuthology-2014-01-14_19:00:22-rados-dumpling-testing-basic-plana/38758$ vi orig.config.yaml \r\nubuntu@teuthology:/a/teuthology-2014-01-14_19:00:22-rados-dumpling-testing-basic-plana/38758$ vi teuthology.log \r\nubuntu@teuthology:/a/teuthology-2014-01-14_19:00:22-rados-dumpling-testing-basic-plana/38758$ vi teuthology.log \r\nubuntu@teuthology:/a/teuthology-2014-01-14_19:00:22-rados-dumpling-testing-basic-plana/38758$ vi teuthology.log \r\n\r\n  File \"/home/teuthworker/teuthology-dumpling/teuthology/orchestra/run.py\", line 267, in run\r\n    r.exitstatus = _check_status(r.exitstatus)\r\n  File \"/home/teuthworker/teuthology-dumpling/teuthology/orchestra/run.py\", line 263, in _check_status\r\n    raise CommandFailedError(command=r.command, exitstatus=status, node=host)\r\nCommandFailedError: Command failed on 10.214.132.8 with status 1: 'mkdir -p -- /home/ubuntu/cephtest/mnt.0/client.0/tmp && cd -- /home/ubuntu/cephtest/mnt.0/client.0/tmp && CEPH_CLI_TEST_DUP_COMMAND=1 CEPH_REF=ee9fc590a556354b54a174a4790c4142949d7409 TESTDIR=\"/home/ubuntu/cephtest\" CEPH_ID=\"0\" PYTHONPATH=\"$PYTHONPATH:/home/ubuntu/cephtest/binary/usr/local/lib/python2.7/dist-packages:/home/ubuntu/cephtest/binary/usr/local/lib/python2.6/dist-packages\" /home/ubuntu/cephtest/adjust-ulimits ceph-coverage /home/ubuntu/cephtest/archive/coverage /home/ubuntu/cephtest/workunit.client.0/rest/test.py'\"\r\n\r\nOriginal config:\r\n\r\n\"description: rados/singleton/{all/rest-api.yaml fs/btrfs.yaml msgr-failures/many.yaml}\r\nemail: null\r\njob_id: '38758'\r\nkernel:\r\n  kdb: true\r\n  sha1: f2be82b0058e90b5d9ac2cb896b4914276fb50ef\r\nlast_in_suite: false\r\nmachine_type: plana\r\nname: teuthology-2014-01-14_19:00:22-rados-dumpling-testing-basic-plana\r\nnuke-on-error: true\r\nos_type: ubuntu\r\noverrides:\r\n  admin_socket:\r\n    branch: dumpling\r\n  ceph:\r\n    conf:\r\n      global:\r\n        ms inject socket failures: 500\r\n      mon:\r\n        debug mon: 20\r\n        debug ms: 1\r\n        debug paxos: 20\r\n      osd:\r\n        debug ms: 1\r\n        debug osd: 5\r\n        osd op thread timeout: 60\r\n    fs: btrfs\r\n    log-whitelist:\r\n    - slow request\r\n    sha1: ee9fc590a556354b54a174a4790c4142949d7409\r\n  ceph-deploy:\r\n    branch:\r\n      dev: dumpling\r\n    conf:\r\n      client:\r\n        log file: /var/log/ceph/ceph-$name.$pid.log\r\n      mon:\r\n        debug mon: 1\r\n        debug ms: 20\r\n        debug paxos: 20\r\n        osd default pool size: 2\r\n  install:\r\n    ceph:\r\n      sha1: ee9fc590a556354b54a174a4790c4142949d7409\r\n  s3tests:\r\n    branch: dumpling\r\n  workunit:\r\n    sha1: ee9fc590a556354b54a174a4790c4142949d7409\r\nowner: scheduled_teuthology@teuthology\r\nroles:\r\n- - mon.0\r\n  - mon.1\r\n  - mon.2\r\n  - mds.a\r\n  - osd.0\r\n  - osd.1\r\n  - osd.2\r\n  - client.0\r\ntasks:\r\n- chef: null\r\n- clock.check: null\r\n- install: null\r\n- ceph:\r\n    log-whitelist:\r\n    - wrongly marked me down\r\n    - had wrong client addr\r\n- rest-api:\r\n  - client.0\r\n- workunit:\r\n    clients:\r\n      all:\r\n      - rest/test.py\r\nteuthology_branch: dumpling\r\nverbose: true\r\nubuntu@teuthology:/a/teuthology-2014-01-14_19:00:22-rados-dumpling-testing-basic-p\"\r\n\r\nSummary:\r\n\r\n\"\r\ndescription: rados/singleton/{all/rest-api.yaml fs/btrfs.yaml msgr-failures/many.yaml}\r\nduration: 145.53783512115479\r\nfailure_reason: 'Command failed on 10.214.132.8 with status 1: ''mkdir -p -- /home/ubuntu/cephtest/mnt.0/client.0/tmp\r\n  && cd -- /home/ubuntu/cephtest/mnt.0/client.0/tmp && CEPH_CLI_TEST_DUP_COMMAND=1\r\n  CEPH_REF=ee9fc590a556354b54a174a4790c4142949d7409 TESTDIR=\"/home/ubuntu/cephtest\"\r\n  CEPH_ID=\"0\" PYTHONPATH=\"$PYTHONPATH:/home/ubuntu/cephtest/binary/usr/local/lib/python2.7/dist-packages:/home/ubuntu/cephtest/binary/usr/local/lib/python2.6/dist-packages\"\r\n  /home/ubuntu/cephtest/adjust-ulimits ceph-coverage /home/ubuntu/cephtest/archive/coverage\r\n  /home/ubuntu/cephtest/workunit.client.0/rest/test.py'''\r\nflavor: basic\r\nmon.0-kernel-sha1: f2be82b0058e90b5d9ac2cb896b4914276fb50ef\r\nowner: scheduled_teuthology@teuthology\r\nsuccess: false\"","start_date":"2014-01-15","done_ratio":0,"custom_fields":[{"id":1,"name":"Source","value":"Q/A"},{"id":2,"name":"Backport","value":""},{"id":3,"name":"Tags","value":""},{"id":4,"name":"Severity","value":"3 - minor"},{"id":5,"name":"Reviewed","value":""}],"created_on":"2014-01-15T22:09:26Z","updated_on":"2014-01-15T22:09:26Z"},{"id":7153,"project":{"id":14,"name":"teuthology"},"tracker":{"id":1,"name":"Bug"},"status":{"id":1,"name":"New"},"priority":{"id":5,"name":"High"},"author":{"id":1052,"name":"Alfredo Deza"},"assigned_to":{"id":684,"name":"Sandon Van Ness"},"subject":"unable to find SHA1 from ceph.com git mirror","description":"Tests are failing because some hash does not exist in the git mirror\r\n\r\nLog excerpt:\r\n\r\n<pre>\r\n2014-01-14T21:36:51.490 INFO:teuthology.orchestra.run.err:[10.214.138.60]: error: Failed connect to ceph.com:80; No such file or directory (curl_result = 7, http_code = 0, sha1 = c20860ae0a8c52f5ff4b55eb9581729f4e5dcfe9)\r\n2014-01-14T21:36:51.490 INFO:teuthology.orchestra.run.err:[10.214.138.60]: error: Unable to find 0ae72e3adb392beb926336b22386af7b81104d45 under http://ceph.com/git/ceph-qa-chef.git\r\n2014-01-14T21:36:51.490 INFO:teuthology.orchestra.run.err:[10.214.138.60]: Cannot obtain needed blob 0ae72e3adb392beb926336b22386af7b81104d45\r\n2014-01-14T21:36:51.491 INFO:teuthology.orchestra.run.err:[10.214.138.60]: while processing commit b7120725a9c10e6f42d198700c2e80fe16c74db0.\r\n</pre>\r\n\r\nFull log link to one of the failures: http://qa-proxy.ceph.com/teuthology/teuthology-2014-01-13_01:10:26-ceph-deploy-master-testing-basic-vps/36642/teuthology.log","start_date":"2014-01-15","done_ratio":0,"custom_fields":[{"id":1,"name":"Source","value":"Q/A"},{"id":2,"name":"Backport","value":""},{"id":3,"name":"Tags","value":""},{"id":4,"name":"Severity","value":"3 - minor"},{"id":5,"name":"Reviewed","value":""}],"created_on":"2014-01-15T17:47:11Z","updated_on":"2014-01-15T17:47:11Z"},{"id":7152,"project":{"id":14,"name":"teuthology"},"tracker":{"id":1,"name":"Bug"},"status":{"id":1,"name":"New"},"priority":{"id":5,"name":"High"},"author":{"id":1052,"name":"Alfredo Deza"},"assigned_to":{"id":684,"name":"Sandon Van Ness"},"subject":"ceph-fuse package cannot be installed","description":"A few tests are failing because this package cannot be found:\r\n\r\n<pre>\r\n2014-01-15T00:52:58.136 ERROR:teuthology.contextutil:Saw exception from nested tasks\r\nTraceback (most recent call last):\r\n  File \"/home/teuthworker/teuthology-master/teuthology/contextutil.py\", line 25, in nested\r\n    vars.append(enter())\r\n  File \"/usr/lib/python2.7/contextlib.py\", line 17, in __enter__\r\n    return self.gen.next()\r\n  File \"/home/teuthworker/teuthology-master/teuthology/task/install.py\", line 809, in install\r\n    install_packages(ctx, install_info, config)\r\n  File \"/home/teuthworker/teuthology-master/teuthology/task/install.py\", line 529, in install_packages\r\n    ctx, remote, pkgs[system_type], config)\r\n  File \"/home/teuthworker/teuthology-master/teuthology/parallel.py\", line 83, in __exit__\r\n    for result in self:\r\n  File \"/home/teuthworker/teuthology-master/teuthology/parallel.py\", line 100, in next\r\n    resurrect_traceback(result)\r\n  File \"/home/teuthworker/teuthology-master/teuthology/parallel.py\", line 19, in capture_traceback\r\n    return func(*args, **kwargs)\r\n  File \"/home/teuthworker/teuthology-master/teuthology/task/install.py\", line 465, in _update_rpm_package_list_and_install\r\n    stderr=pk_err_mess)\r\n  File \"/home/teuthworker/teuthology-master/teuthology/orchestra/remote.py\", line 47, in run\r\n    r = self._runner(client=self.ssh, **kwargs)\r\n  File \"/home/teuthworker/teuthology-master/teuthology/orchestra/run.py\", line 271, in run\r\n    r.exitstatus = _check_status(r.exitstatus)\r\n  File \"/home/teuthworker/teuthology-master/teuthology/orchestra/run.py\", line 267, in _check_status\r\n    raise CommandFailedError(command=r.command, exitstatus=status, node=host)\r\nCommandFailedError: Command failed on 10.214.138.123 with status 1: 'sudo yum install ceph-fuse-0.74 -y'\r\n2014-01-15T00:52:58.137 ERROR:teuthology.run_tasks:Saw exception from tasks.\r\nTraceback (most recent call last):\r\n  File \"/home/teuthworker/teuthology-master/teuthology/run_tasks.py\", line 33, in run_tasks\r\n    manager.__enter__()\r\n  File \"/usr/lib/python2.7/contextlib.py\", line 17, in __enter__\r\n    return self.gen.next()\r\n  File \"/home/teuthworker/teuthology-master/teuthology/task/install.py\", line 1155, in task\r\n    lambda: install(ctx=ctx, config=dict(\r\n  File \"/usr/lib/python2.7/contextlib.py\", line 17, in __enter__\r\n    return self.gen.next()\r\n  File \"/home/teuthworker/teuthology-master/teuthology/contextutil.py\", line 25, in nested\r\n    vars.append(enter())\r\n  File \"/usr/lib/python2.7/contextlib.py\", line 17, in __enter__\r\n    return self.gen.next()\r\n  File \"/home/teuthworker/teuthology-master/teuthology/task/install.py\", line 809, in install\r\n    install_packages(ctx, install_info, config)\r\n  File \"/home/teuthworker/teuthology-master/teuthology/task/install.py\", line 529, in install_packages\r\n    ctx, remote, pkgs[system_type], config)\r\n  File \"/home/teuthworker/teuthology-master/teuthology/parallel.py\", line 83, in __exit__\r\n    for result in self:\r\n  File \"/home/teuthworker/teuthology-master/teuthology/parallel.py\", line 100, in next\r\n    resurrect_traceback(result)\r\n  File \"/home/teuthworker/teuthology-master/teuthology/parallel.py\", line 19, in capture_traceback\r\n    return func(*args, **kwargs)\r\n  File \"/home/teuthworker/teuthology-master/teuthology/task/install.py\", line 465, in _update_rpm_package_list_and_install\r\n    stderr=pk_err_mess)\r\n  File \"/home/teuthworker/teuthology-master/teuthology/orchestra/remote.py\", line 47, in run\r\n    r = self._runner(client=self.ssh, **kwargs)\r\n  File \"/home/teuthworker/teuthology-master/teuthology/orchestra/run.py\", line 271, in run\r\n    r.exitstatus = _check_status(r.exitstatus)\r\n  File \"/home/teuthworker/teuthology-master/teuthology/orchestra/run.py\", line 267, in _check_status\r\n    raise CommandFailedError(command=r.command, exitstatus=status, node=host)\r\nCommandFailedError: Command failed on 10.214.138.123 with status 1: 'sudo yum install ceph-fuse-0.74 -y'\r\n</pre>\r\n\r\nFull logs for the above excerpt: http://qa-proxy.ceph.com/teuthology/teuthology-2014-01-13_01:10:26-ceph-deploy-master-testing-basic-vps/36704/teuthology.log\r\n","start_date":"2014-01-15","done_ratio":0,"custom_fields":[{"id":1,"name":"Source","value":"Q/A"},{"id":2,"name":"Backport","value":""},{"id":3,"name":"Tags","value":""},{"id":4,"name":"Severity","value":"3 - minor"},{"id":5,"name":"Reviewed","value":""}],"created_on":"2014-01-15T17:43:41Z","updated_on":"2014-01-15T17:43:41Z"},{"id":7112,"project":{"id":14,"name":"teuthology"},"tracker":{"id":5,"name":"Tasks"},"status":{"id":1,"name":"New"},"priority":{"id":5,"name":"High"},"author":{"id":1076,"name":"Zack Cerza"},"subject":"Teuthology performance testing tracker","description":"","start_date":"2013-10-28","done_ratio":0,"custom_fields":[{"id":3,"name":"Tags","value":""},{"id":5,"name":"Reviewed","value":""}],"created_on":"2014-01-07T18:24:40Z","updated_on":"2014-01-07T18:25:51Z","story_points":null},{"id":7111,"project":{"id":14,"name":"teuthology"},"tracker":{"id":2,"name":"Feature"},"status":{"id":1,"name":"New"},"priority":{"id":4,"name":"Normal"},"author":{"id":789,"name":"Loic Dachary"},"subject":"pulpito: display timezone","description":"It would help if http://pulpito.ceph.com/ displayed the timezone to figure out when a run actually happened even when looking at it from france. I guess it's PDT but it would not hurt to not have to guess.\r\n","start_date":"2014-01-07","done_ratio":0,"custom_fields":[{"id":1,"name":"Source","value":"other"},{"id":3,"name":"Tags","value":""},{"id":5,"name":"Reviewed","value":""},{"id":6,"name":"User Impact","value":""}],"created_on":"2014-01-07T16:12:39Z","updated_on":"2014-01-07T16:12:39Z","story_points":null},{"id":7080,"project":{"id":14,"name":"teuthology"},"tracker":{"id":1,"name":"Bug"},"status":{"id":1,"name":"New"},"priority":{"id":5,"name":"High"},"author":{"id":1052,"name":"Alfredo Deza"},"assigned_to":{"id":684,"name":"Sandon Van Ness"},"subject":"redhat-lsb package cannot be installed","description":"Apparently, chef-solo times out waiting to connect.\r\n\r\nNot entirely sure if this is entirely a problem on our end (we've seen this exact same one before). But\r\ncreating a ticket regardless so we can track it even it if appears to be invalid.\r\n\r\nLog output explaining the problem:\r\n\r\n<pre>\r\n2014-01-01T02:38:38.913 INFO:teuthology.orchestra.run.out:[10.214.138.97]: [2014-01-01T10:38:37-05:00] ERROR: package[redhat-lsb] (ceph-qa::redhat line 96) had an error: Timeout::Error: execution expired\r\n2014-01-01T02:38:38.914 INFO:teuthology.orchestra.run.out:[10.214.138.97]: \u001B[0m\r\n2014-01-01T02:38:38.914 INFO:teuthology.orchestra.run.out:[10.214.138.97]: ================================================================================\u001B[0m\r\n2014-01-01T02:38:38.914 INFO:teuthology.orchestra.run.out:[10.214.138.97]: \u001B[31mError executing action `install` on resource 'package[redhat-lsb]'\u001B[0m\r\n2014-01-01T02:38:38.914 INFO:teuthology.orchestra.run.out:[10.214.138.97]: ================================================================================\u001B[0m\r\n2014-01-01T02:38:38.914 INFO:teuthology.orchestra.run.out:[10.214.138.97]: \r\n2014-01-01T02:38:38.915 INFO:teuthology.orchestra.run.out:[10.214.138.97]: \u001B[0m\r\n2014-01-01T02:38:38.915 INFO:teuthology.orchestra.run.out:[10.214.138.97]: Timeout::Error\u001B[0m\r\n2014-01-01T02:38:38.915 INFO:teuthology.orchestra.run.out:[10.214.138.97]: --------------\u001B[0m\r\n2014-01-01T02:38:38.915 INFO:teuthology.orchestra.run.out:[10.214.138.97]: execution expired\u001B[0m\r\n2014-01-01T02:38:38.915 INFO:teuthology.orchestra.run.out:[10.214.138.97]: \r\n2014-01-01T02:38:38.915 INFO:teuthology.orchestra.run.out:[10.214.138.97]: \u001B[0m\r\n2014-01-01T02:38:38.916 INFO:teuthology.orchestra.run.out:[10.214.138.97]: Resource Declaration:\u001B[0m\r\n2014-01-01T02:38:38.916 INFO:teuthology.orchestra.run.out:[10.214.138.97]: ---------------------\u001B[0m\r\n2014-01-01T02:38:38.916 INFO:teuthology.orchestra.run.out:[10.214.138.97]: # In /tmp/solo-from-scratch.9bTGTA2wTs9Z/cookbooks/ceph-qa/recipes/redhat.rb\r\n2014-01-01T02:38:38.916 INFO:teuthology.orchestra.run.out:[10.214.138.97]: \r\n2014-01-01T02:38:38.916 INFO:teuthology.orchestra.run.out:[10.214.138.97]:  96: package 'redhat-lsb'\r\n2014-01-01T02:38:38.917 INFO:teuthology.orchestra.run.out:[10.214.138.97]:  97: package 'sysstat'\r\n2014-01-01T02:38:38.917 INFO:teuthology.orchestra.run.out:[10.214.138.97]: \u001B[0m\r\n2014-01-01T02:38:38.917 INFO:teuthology.orchestra.run.out:[10.214.138.97]: \r\n2014-01-01T02:38:38.917 INFO:teuthology.orchestra.run.out:[10.214.138.97]: \u001B[0m\r\n2014-01-01T02:38:38.917 INFO:teuthology.orchestra.run.out:[10.214.138.97]: Compiled Resource:\u001B[0m\r\n2014-01-01T02:38:38.917 INFO:teuthology.orchestra.run.out:[10.214.138.97]: ------------------\u001B[0m\r\n2014-01-01T02:38:38.918 INFO:teuthology.orchestra.run.out:[10.214.138.97]: # Declared in /tmp/solo-from-scratch.9bTGTA2wTs9Z/cookbooks/ceph-qa/recipes/redhat.rb:96:in `from_file'\r\n2014-01-01T02:38:38.918 INFO:teuthology.orchestra.run.out:[10.214.138.97]: \r\n2014-01-01T02:38:38.918 INFO:teuthology.orchestra.run.out:[10.214.138.97]: package(\"redhat-lsb\") do\r\n2014-01-01T02:38:38.918 INFO:teuthology.orchestra.run.out:[10.214.138.97]:   retries 0\r\n2014-01-01T02:38:38.918 INFO:teuthology.orchestra.run.out:[10.214.138.97]:   package_name \"redhat-lsb\"\r\n2014-01-01T02:38:38.918 INFO:teuthology.orchestra.run.out:[10.214.138.97]:   action :install\r\n2014-01-01T02:38:38.919 INFO:teuthology.orchestra.run.out:[10.214.138.97]:   recipe_name \"redhat\"\r\n2014-01-01T02:38:38.919 INFO:teuthology.orchestra.run.out:[10.214.138.97]:   cookbook_name :\"ceph-qa\"\r\n2014-01-01T02:38:38.919 INFO:teuthology.orchestra.run.out:[10.214.138.97]:   version \"4.0-7.el6\"\r\n2014-01-01T02:38:38.919 INFO:teuthology.orchestra.run.out:[10.214.138.97]:   retry_delay 2\r\n2014-01-01T02:38:38.919 INFO:teuthology.orchestra.run.out:[10.214.138.97]: end\r\n2014-01-01T02:38:38.919 INFO:teuthology.orchestra.run.out:[10.214.138.97]: \u001B[0m\r\n2014-01-01T02:38:38.920 INFO:teuthology.orchestra.run.out:[10.214.138.97]: \r\n2014-01-01T02:38:38.920 INFO:teuthology.orchestra.run.out:[10.214.138.97]: \u001B[0m\r\n2014-01-01T02:38:38.928 INFO:teuthology.orchestra.run.out:[10.214.138.97]: [2014-01-01T10:22:20-05:00] INFO: Forking chef instance to converge...\r\n2014-01-01T02:38:38.928 INFO:teuthology.orchestra.run.out:[10.214.138.97]: [2014-01-01T10:22:20-05:00] DEBUG: Fork successful. Waiting for new chef pid: 2755\r\n2014-01-01T02:38:38.928 INFO:teuthology.orchestra.run.out:[10.214.138.97]: [2014-01-01T10:38:37-05:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)\r\n</pre>","start_date":"2014-01-02","done_ratio":0,"custom_fields":[{"id":1,"name":"Source","value":"other"},{"id":2,"name":"Backport","value":""},{"id":3,"name":"Tags","value":""},{"id":4,"name":"Severity","value":"3 - minor"},{"id":5,"name":"Reviewed","value":""}],"created_on":"2014-01-02T14:13:37Z","updated_on":"2014-01-06T14:25:17Z"},{"id":7079,"project":{"id":14,"name":"teuthology"},"tracker":{"id":1,"name":"Bug"},"status":{"id":1,"name":"New"},"priority":{"id":6,"name":"Urgent"},"author":{"id":1052,"name":"Alfredo Deza"},"assigned_to":{"id":684,"name":"Sandon Van Ness"},"subject":"Ceph RPM not Found","description":"Nightly ceph-deploy tests are failing because the Ceph RPM is not found.\r\n\r\nOutput of a run with that problem:\r\n\r\n<pre>\r\n2014-01-01T02:10:49.491 INFO:teuthology.task.install:Installing packages: ceph-fuse, librbd1, librados2, ceph-test, python-ceph, librbd1, librados2 on remote rpm x86_64\r\n2014-01-01T02:10:49.492 DEBUG:teuthology.orchestra.run:Running [10.214.138.178]: 'wget http://gitbuilder.ceph.com/ceph-rpm-centos6-x86_64-basic/sha1/fe3fd5fb4aa6327256dfaf731914dc4f79b0d44e/noarch/ceph-release-1-0.el6.noarch.rpm'\r\n2014-01-01T02:10:49.494 DEBUG:teuthology.orchestra.run:Running [10.214.138.186]: 'lsb_release -is'\r\n2014-01-01T02:10:49.522 INFO:teuthology.orchestra.run.err:[10.214.138.178]: --2014-01-01 05:10:49--  http://gitbuilder.ceph.com/ceph-rpm-centos6-x86_64-basic/sha1/fe3fd5fb4aa6327256dfaf731914dc4f79b0d44e/noarch/ceph-release-1-0.el6.noarch.rpm\r\n2014-01-01T02:10:49.523 INFO:teuthology.orchestra.run.err:[10.214.138.178]: Resolving gitbuilder.ceph.com... 64.90.32.38\r\n2014-01-01T02:10:49.524 INFO:teuthology.orchestra.run.err:[10.214.138.178]: Connecting to gitbuilder.ceph.com|64.90.32.38|:80... connected.\r\n2014-01-01T02:10:49.526 INFO:teuthology.orchestra.run.err:[10.214.138.178]: HTTP request sent, awaiting response... 404 Not Found\r\n2014-01-01T02:10:49.526 INFO:teuthology.orchestra.run.err:[10.214.138.178]: 2014-01-01 05:10:49 ERROR 404: Not Found.\r\n</pre>\r\n\r\nFull log link to one machine: http://qa-proxy.ceph.com/teuthology/teuthology-2014-01-01_01:10:07-ceph-deploy-master-testing-basic-vps/21101/teuthology.log\r\n\r\n","start_date":"2014-01-02","done_ratio":0,"custom_fields":[{"id":1,"name":"Source","value":"other"},{"id":2,"name":"Backport","value":""},{"id":3,"name":"Tags","value":""},{"id":4,"name":"Severity","value":"3 - minor"},{"id":5,"name":"Reviewed","value":""}],"created_on":"2014-01-02T14:06:17Z","updated_on":"2014-01-15T13:23:38Z"},{"id":7074,"project":{"id":14,"name":"teuthology"},"tracker":{"id":1,"name":"Bug"},"status":{"id":1,"name":"New"},"priority":{"id":4,"name":"Normal"},"author":{"id":1076,"name":"Zack Cerza"},"subject":"AssertionError in teuthology-coverage","description":"Seen on this run:\r\nsage-2013-12-30_20:59:21-krbd-next-for-stable-3.10.24-basic-plana\r\n\r\n<pre>\r\nTraceback (most recent call last):\r\n  File \"/var/lib/teuthworker/teuthology-master/virtualenv/bin/teuthology-coverage\", line 9, in <module>\r\n    load_entry_point('teuthology==0.0.1', 'console_scripts', 'teuthology-coverage')()\r\n  File \"/home/teuthworker/teuthology-master/scripts/coverage.py\", line 7, in main\r\n    teuthology.coverage.main(parse_args())\r\n  File \"/home/teuthworker/teuthology-master/teuthology/coverage.py\", line 111, in main\r\n    analyze(args)\r\n  File \"/home/teuthworker/teuthology-master/teuthology/coverage.py\", line 138, in analyze\r\n    assert len(test_summaries) > 0\r\nAssertionError\r\n</pre>","start_date":"2013-12-31","done_ratio":0,"custom_fields":[{"id":1,"name":"Source","value":"other"},{"id":2,"name":"Backport","value":""},{"id":3,"name":"Tags","value":""},{"id":4,"name":"Severity","value":"3 - minor"},{"id":5,"name":"Reviewed","value":""}],"created_on":"2013-12-31T15:50:36Z","updated_on":"2013-12-31T15:50:36Z"},{"id":7055,"project":{"id":14,"name":"teuthology"},"tracker":{"id":1,"name":"Bug"},"status":{"id":1,"name":"New"},"priority":{"id":4,"name":"Normal"},"author":{"id":843,"name":"Warren Usui"},"subject":"pulpito: Some jobs that have passed are still listed as running by Pulpito.","description":"http://pulpito.ceph.com/sage-2013-12-22_12:21:25-rados:thrash-wip-cache-testing-basic-plana/ has 3 jobs that are listed as still running: 11952, 11958, and 11983.  If you look at the teuthology.log files for these jobs, all 3 appear to have passed.","start_date":"2013-12-22","done_ratio":0,"custom_fields":[{"id":1,"name":"Source","value":"other"},{"id":2,"name":"Backport","value":""},{"id":3,"name":"Tags","value":""},{"id":4,"name":"Severity","value":"3 - minor"},{"id":5,"name":"Reviewed","value":""}],"created_on":"2013-12-23T07:50:57Z","updated_on":"2013-12-23T07:50:57Z"},{"id":7045,"project":{"id":14,"name":"teuthology"},"tracker":{"id":1,"name":"Bug"},"status":{"id":1,"name":"New"},"priority":{"id":4,"name":"Normal"},"author":{"id":1076,"name":"Zack Cerza"},"assigned_to":{"id":1076,"name":"Zack Cerza"},"fixed_version":{"id":271,"name":"v0.76"},"subject":"Rethink which runs to show on pulpito's front page","description":"","start_date":"2013-12-20","done_ratio":0,"custom_fields":[{"id":1,"name":"Source","value":"other"},{"id":2,"name":"Backport","value":""},{"id":3,"name":"Tags","value":""},{"id":4,"name":"Severity","value":"3 - minor"},{"id":5,"name":"Reviewed","value":""}],"created_on":"2013-12-20T19:40:27Z","updated_on":"2013-12-20T19:40:27Z"},{"id":7028,"project":{"id":14,"name":"teuthology"},"tracker":{"id":2,"name":"Feature"},"status":{"id":1,"name":"New"},"priority":{"id":4,"name":"Normal"},"author":{"id":843,"name":"Warren Usui"},"subject":"pulpito reporting -- it would be nice to see reports of dead/failed/running jobs","description":"Pulpito is great as far as showing the status of a run in general, but when one sees that a suite has 20 failed, 30 dead, and 10 still running jobs, one still needs to look at a bunch of files to figure out whats going on with these runs.\r\n\r\nIt would be cool if there were somewhere we can get a report like:\r\n24 -- killed while still waiting for machines\r\n5 -- Host not found error\r\n1 -- <Unique message for this one run>\r\n.\r\n.\r\n.\r\n\r\nI started to write a python script to following links and parse the html, but I think that it makes more sense to have a task at the database level to generate\r\nthis report,","start_date":"2013-12-18","done_ratio":0,"custom_fields":[{"id":1,"name":"Source","value":"other"},{"id":3,"name":"Tags","value":""},{"id":5,"name":"Reviewed","value":""},{"id":6,"name":"User Impact","value":""}],"created_on":"2013-12-18T09:05:45Z","updated_on":"2013-12-18T15:42:51Z","story_points":null},{"id":7021,"project":{"id":14,"name":"teuthology"},"tracker":{"id":1,"name":"Bug"},"status":{"id":1,"name":"New"},"priority":{"id":4,"name":"Normal"},"author":{"id":716,"name":"David Zafman"},"subject":"Long hostnames break schedule_suite.sh","description":"A hostname of longer than 14 characters won't work with schedule_suite.sh possibly due to locking owner length limit.\r\n\r\n2013-12-17T09:21:13.345 INFO:teuthology.run:Summary data:\r\n{description: 'rados/thrash/{clusters/fixed-2.yaml fs/btrfs.yaml msgr-failures/few.yaml\r\n    thrashers/default.yaml workloads/radosbench.yaml}', failure_reason: 'machine ubuntu@plana25.front.sepia.ceph.com\r\n    is locked by scheduled_dzafman@macbookpro-ubu, not scheduled_dzafman@macbookpro-ubuntu-build',\r\n  owner: scheduled_dzafman@macbookpro-ubuntu-build, sentry_event: 'http://sentry.ceph.com/inktank/teuthology/search?q=93b191b95a184da7b9e6816b9ed94a3c',\r\n  success: false}\r\n\r\nThe owner is chopped in the output of teuthology-lock --list\r\n\r\n  \"locked_by\": \"scheduled_dzafman@macbookpro-ubu\",\r\n","start_date":"2013-12-17","done_ratio":0,"custom_fields":[{"id":1,"name":"Source","value":"other"},{"id":2,"name":"Backport","value":""},{"id":3,"name":"Tags","value":""},{"id":4,"name":"Severity","value":"3 - minor"},{"id":5,"name":"Reviewed","value":""}],"created_on":"2013-12-17T17:49:36Z","updated_on":"2013-12-17T17:49:36Z"},{"id":7008,"project":{"id":14,"name":"teuthology"},"tracker":{"id":2,"name":"Feature"},"status":{"id":1,"name":"New"},"priority":{"id":4,"name":"Normal"},"author":{"id":3,"name":"Sage Weil"},"assigned_to":{"id":1076,"name":"Zack Cerza"},"fixed_version":{"id":271,"name":"v0.76"},"subject":"pulpito: show pass/fail stats by machine","description":"","done_ratio":0,"custom_fields":[{"id":1,"name":"Source","value":"other"},{"id":3,"name":"Tags","value":""},{"id":5,"name":"Reviewed","value":""},{"id":6,"name":"User Impact","value":""}],"created_on":"2013-12-16T04:54:09Z","updated_on":"2013-12-20T19:39:31Z","story_points":null},{"id":7003,"project":{"id":14,"name":"teuthology"},"tracker":{"id":1,"name":"Bug"},"status":{"id":1,"name":"New"},"priority":{"id":4,"name":"Normal"},"author":{"id":843,"name":"Warren Usui"},"assigned_to":{"id":843,"name":"Warren Usui"},"subject":"Docstrings for orchestra functions and classes are needed.","description":"Docstrings are missing from orchestra py files.","start_date":"2013-12-13","done_ratio":0,"custom_fields":[{"id":1,"name":"Source","value":"other"},{"id":2,"name":"Backport","value":""},{"id":3,"name":"Tags","value":""},{"id":4,"name":"Severity","value":"3 - minor"},{"id":5,"name":"Reviewed","value":""}],"created_on":"2013-12-14T00:08:42Z","updated_on":"2013-12-14T00:12:57Z"},{"id":7002,"project":{"id":14,"name":"teuthology"},"tracker":{"id":1,"name":"Bug"},"status":{"id":1,"name":"New"},"priority":{"id":4,"name":"Normal"},"author":{"id":843,"name":"Warren Usui"},"assigned_to":{"id":843,"name":"Warren Usui"},"subject":"Docstrings should be added to misc functions","description":"Docstrings are missing from teuthology/misc.py","start_date":"2013-12-13","done_ratio":0,"custom_fields":[{"id":1,"name":"Source","value":"other"},{"id":2,"name":"Backport","value":""},{"id":3,"name":"Tags","value":""},{"id":4,"name":"Severity","value":"3 - minor"},{"id":5,"name":"Reviewed","value":""}],"created_on":"2013-12-13T23:59:38Z","updated_on":"2013-12-14T00:00:48Z"},{"id":7001,"project":{"id":14,"name":"teuthology"},"tracker":{"id":1,"name":"Bug"},"status":{"id":1,"name":"New"},"priority":{"id":4,"name":"Normal"},"author":{"id":843,"name":"Warren Usui"},"assigned_to":{"id":843,"name":"Warren Usui"},"subject":"Local functions in misc should be distinguished.","description":"get_test_user, gen_addresses, and remove_lines_from_file should be _get_test_user, _gen_addresses and _remove_lines_from_files","start_date":"2013-12-13","done_ratio":0,"custom_fields":[{"id":1,"name":"Source","value":"other"},{"id":2,"name":"Backport","value":""},{"id":3,"name":"Tags","value":""},{"id":4,"name":"Severity","value":"3 - minor"},{"id":5,"name":"Reviewed","value":""}],"created_on":"2013-12-13T23:56:53Z","updated_on":"2013-12-14T00:26:59Z"},{"id":7000,"project":{"id":14,"name":"teuthology"},"tracker":{"id":1,"name":"Bug"},"status":{"id":1,"name":"New"},"priority":{"id":4,"name":"Normal"},"author":{"id":1330,"name":"Steven Lang"},"subject":"Teuthology README doesn't adequately provide a quick start","description":"Reading the README for teuthology, I had the impression that the lock server was something that was only used when --lock was given; but trying to run it gives an error connecting to the lock server. I had to look elsewhere to learn about check-locks.\r\n\r\nThe example should probably include check-locks: false, and the section on locking should reflect that it is the default.","start_date":"2013-12-13","done_ratio":0,"custom_fields":[{"id":1,"name":"Source","value":"other"},{"id":2,"name":"Backport","value":""},{"id":3,"name":"Tags","value":""},{"id":4,"name":"Severity","value":"3 - minor"},{"id":5,"name":"Reviewed","value":""}],"created_on":"2013-12-13T23:17:57Z","updated_on":"2013-12-13T23:17:57Z"},{"id":6978,"project":{"id":14,"name":"teuthology"},"tracker":{"id":2,"name":"Feature"},"status":{"id":1,"name":"New"},"priority":{"id":4,"name":"Normal"},"author":{"id":843,"name":"Warren Usui"},"subject":"Teuthology: The program vs. tasks.","description":"These should probably be decouple more.","start_date":"2013-12-10","done_ratio":0,"custom_fields":[{"id":1,"name":"Source","value":"other"},{"id":3,"name":"Tags","value":""},{"id":5,"name":"Reviewed","value":""},{"id":6,"name":"User Impact","value":""}],"created_on":"2013-12-11T04:36:25Z","updated_on":"2013-12-11T04:40:11Z","story_points":null},{"id":6963,"project":{"id":14,"name":"teuthology"},"tracker":{"id":2,"name":"Feature"},"status":{"id":1,"name":"New"},"priority":{"id":4,"name":"Normal"},"author":{"id":843,"name":"Warren Usui"},"subject":"Decouple teuthology and Inktank's infrastructure","description":"Some planning required before we actually do this.","start_date":"2013-12-10","done_ratio":0,"custom_fields":[{"id":1,"name":"Source","value":"other"},{"id":3,"name":"Tags","value":""},{"id":5,"name":"Reviewed","value":""},{"id":6,"name":"User Impact","value":""}],"created_on":"2013-12-10T18:56:13Z","updated_on":"2013-12-10T19:14:39Z","story_points":null},{"id":6952,"project":{"id":14,"name":"teuthology"},"tracker":{"id":1,"name":"Bug"},"status":{"id":1,"name":"New"},"priority":{"id":4,"name":"Normal"},"author":{"id":843,"name":"Warren Usui"},"assigned_to":{"id":1076,"name":"Zack Cerza"},"subject":"Some overnight teuthology runs generate a whole bunch of output.","description":"I doubt that this is expected behavior, because I am pretty sure no human being is wading through all this information\r\n\r\nThis may also account for some of the jobs that hang overnight and clog the machines.\r\n\r\nThe following is from teuthology-2013-12-06_02:10:30-upgrade-rgw-next-testing-basic-plana/132981\r\n<pre>\r\n2013-12-06T12:25:42.296 INFO:teuthology.orchestra.run.out:[10.214.132.13]: - [794624, 189190865]\r\n2013-12-06T12:25:42.297 INFO:teuthology.orchestra.run.out:[10.214.132.13]: - [802816, 189244032]\r\n2013-12-06T12:25:42.297 INFO:teuthology.orchestra.run.out:[10.214.132.13]: - [811008, 189301014]\r\n2013-12-06T12:25:42.297 INFO:teuthology.orchestra.run.out:[10.214.132.13]: - [819200, 189355850]\r\n2013-12-06T12:25:42.297 INFO:teuthology.orchestra.run.out:[10.214.132.13]: - [827392, 189412832]\r\n2013-12-06T12:25:42.297 INFO:teuthology.orchestra.run.out:[10.214.132.13]: - [835584, 189469814]\r\n2013-12-06T12:25:42.297 INFO:teuthology.orchestra.run.out:[10.214.132.13]: - [843776, 189522982]\r\n2013-12-06T12:25:42.297 INFO:teuthology.orchestra.run.out:[10.214.132.13]: - [851968, 189574957]\r\n2013-12-06T12:25:42.298 INFO:teuthology.orchestra.run.out:[10.214.132.13]: - [860160, 189627886]\r\n2013-12-06T12:25:42.298 INFO:teuthology.orchestra.run.out:[10.214.132.13]: - [868352, 189683914]\r\n</pre>","start_date":"2013-12-07","done_ratio":0,"custom_fields":[{"id":1,"name":"Source","value":"other"},{"id":2,"name":"Backport","value":""},{"id":3,"name":"Tags","value":""},{"id":4,"name":"Severity","value":"3 - minor"},{"id":5,"name":"Reviewed","value":""}],"created_on":"2013-12-07T21:53:36Z","updated_on":"2014-01-07T17:37:28Z"},{"id":6929,"project":{"id":14,"name":"teuthology"},"tracker":{"id":1,"name":"Bug"},"status":{"id":13,"name":"Need Review"},"priority":{"id":4,"name":"Normal"},"author":{"id":843,"name":"Warren Usui"},"subject":"Downburst documentation is bad.","description":"README.rst says that a downburst option is disk.  That should probably read disk-size.","start_date":"2013-12-03","done_ratio":0,"custom_fields":[{"id":1,"name":"Source","value":"other"},{"id":2,"name":"Backport","value":""},{"id":3,"name":"Tags","value":""},{"id":4,"name":"Severity","value":"3 - minor"},{"id":5,"name":"Reviewed","value":""}],"created_on":"2013-12-04T07:20:11Z","updated_on":"2013-12-04T07:28:11Z"},{"id":6921,"project":{"id":14,"name":"teuthology"},"tracker":{"id":1,"name":"Bug"},"status":{"id":1,"name":"New"},"priority":{"id":4,"name":"Normal"},"author":{"id":843,"name":"Warren Usui"},"assigned_to":{"id":843,"name":"Warren Usui"},"subject":"teuthology-lock downburst yaml file use is broken","description":"One should be able to indicate a downburst file to use for vps machines in the .teuthology.yaml file.  The lock.py code appears to be broken here.  Also, this should be documented in at least the README.rst file.\r\n","start_date":"2013-12-02","done_ratio":0,"custom_fields":[{"id":1,"name":"Source","value":"other"},{"id":2,"name":"Backport","value":""},{"id":3,"name":"Tags","value":""},{"id":4,"name":"Severity","value":"3 - minor"},{"id":5,"name":"Reviewed","value":""}],"created_on":"2013-12-02T22:14:50Z","updated_on":"2013-12-02T22:14:50Z"}],"total_count":149,"offset":0,"limit":25}
